### ISSUE TITLE
When I set Extra Simulation Days higher, the result of simulation is strange.

### ISSUE THREAD

**Issue by L-M-Sherlock** [PhearTheCeal/anki-optimizer#1]
Here are what I set.

Deck Size : 14600
Extra Simulation Days : 200
Expected Retention : 0.9
assumed to be Log(retention)/Log : 0.9
New Cards a Day : 20
failure penalty : 0
20% ease factor decrease on failure : open
others are default

When Days > 365, there are no more new cards. But the number of reviews still increases.

What's more, when I set the Expected Retention to 0.88, the result is normal.

I don't know how to explain it. Is it a bug?

**Comment by PhearTheCeal** [comment]
Looks like a bug related to turning on 20% ease factor decrease on failure. I'll look into it. Thanks!

**Comment by PhearTheCeal** [comment]
Ah, I see now. Not sure if this is actually a bug. When that feature is turned on the ease factor of a card decreases by 20% every time it is failed. So basically what happens is some cards will be failed so many times that the card's ease factor will bottom out at 130% (the minimum in Anki) at which point the new interval gets calculated like this: `<current interval> * <ease_factor> * <interval_modifier>`, which in the default case for a failed card would be `1 * 1.3 * 1` which gets rounded down to 1 day... essentially the cards interval will never grow again and you will rep it daily for eternity (since this simulator does not support removing leeches).

**Comment by L-M-Sherlock** [comment]
@PhearTheCeal Thanks for your reply! Yes, I also found out the reason. When I set the Interval Modifier to 121%, the result is right. Because `Math.round(1*1.3*1.21)=2` XD.
So, would you like to support it in th future?

**Comment by PhearTheCeal** [comment]
mmm... I dunno. Removing leeches just kinda hides the problem, doesn't it? Like, your Anki settings are so sub-optimal that you literally just have to throw cards away to ever decrease your daily reps. I would hope most people using this simulator have already read Matt's guide on Anki and just use the proper settings.

**Comment by L-M-Sherlock** [comment]
I've just read Matt's guide. I finally know why the simulator has "retiring interval", which Anki hasn't.
What he said is inspiring, while it irrelates to leeches.(Maybe he said it and I missed it?)
In my point, I think leeches result from their bad editing, in other words, they are ill-formulated knowledge. In the condition, I will let Anki suspend them and revise them in the other days. Sometime I will also delete them if them aren't worth my time.
In addition, Anki's default option is suspending those cards if lapsesing 8 times.
Of course, your simulator is pretty good. Thanks for your work. If you could consider to support it, it will be more useful.

**Comment by PhearTheCeal** [comment]
This is now fixed
